'on':
  github:
    branches:
      only: master
jobs:
  CurriculumTraining:
    resources:
      instance-type: A100
    uses: script@v1
    inputs:
      workspace:
        type: volume
    with:
      image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime
      script: |
        pip install stable-baselines3==2.2.1
        pip install gym==0.26.2 gymnasium==0.29.1
        pip install numpy
        pip install tensorboard
        pip install matplotlib
        pip install psutil
        pip install cloudpickle
        
        # Run your training script
        python full_script.py
